// Central icon mapping: re-export selected lucide icons with aliases
export {
  ShoppingCart as ShoppingBag,
  ShoppingCart as ShoppingCartIcon,
  User as UserIcon,
  Search as SearchIcon,
  Menu as MenuIcon,
  X as XIcon,
  ArrowLeftRight,
  Store,
  Store as StoreIcon,
  ChevronDown,
  ChevronRight,
  Sparkles,
  Tag,
  Building2,
  Sun,
  Moon,
  Lock,
  Instagram,
  Facebook,
  Twitter,
  Mail,
  MapPin,
  Phone,
  MessageCircle as WhatsApp,
  Trash2,
  Minus,
  Plus,
  Star,
  Heart,
  ArrowRight,
  ShieldCheck,
  Truck,
  RotateCcw,
  Filter,
  SlidersHorizontal,
  LayoutGrid,
  List,
  Percent,
  Check,
  CreditCard,
  MessageSquare,
  Trophy,
  Target,
  TrendingUp,
  Globe,
  Briefcase,
  Package,
} from 'lucide-react';

export default {
  ShoppingBag: (props: any) => null,
};
